name: Continuous integration

on:
  # Manual dispatch for testing
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build construo
        run: ./gradlew assemble
        working-directory: ./construo
      - name: Build test project
        run: ./gradlew test:roastLinuxX64 --stacktrace
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Check code formatting construo
        run: ./gradlew spotlessCheck
        working-directory: ./construo
      - name: Check code formatting test project
        run: ./gradlew spotlessCheck
