name: Publish package to Maven
on:
  # Automatically on every tag starting with v
  push:
    tags:
      - v*
  # Manual dispatch for testing
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Publish package
        run: ./gradlew publishPlugins
        working-directory: ./construo
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.ORG_GRADLE_PROJECT_PLUGIN_PORTAL_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.ORG_GRADLE_PROJECT_PLUGIN_PORTAL_SECRET }}
